#!/bin/bash
sudo git clone https://github.com/omidiyanto/figlet-omi.git
sudo chmod -R 777 figlet-omi
sudo mv figlet-omi/figlet /usr/bin/figlet
sudo mkdir /usr/share/figlet-fonts
sudo mv figlet-omi/* /usr/share/figlet-fonts/
sudo rm -rf figlet-omi
echo "test ansi-shadow"
figlet -f /usr/share/figlet-fonts/ansi-shadow "TEST"
echo "test slant"
figlet -f /usr/share/figlet-fonts/slant "TEST"
echo "Install finish"
